"""
questions.py (route)
----------------------
GET /api/questions/{session_id} — Generate (or return cached) questions.
GET /api/debug/chunks/{session_id} — debug: resume section chunks + per-source
    question contribution.
"""

import logging

from fastapi import APIRouter, HTTPException

from app.services.session_store import session_store
from app.services import question_service

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/api/questions/{session_id}")
def get_questions(session_id: str, total: int = 12, role: str = "", jd: str = ""):
    """
    Assemble interview questions from three sources:
      - 5 technical questions retrieved from the dataset via FAISS (resume-matched)
      - 4 project-specific questions generated by Gemini from the projects section
      - 3 HR & Behavioral questions randomly sampled from the dataset
    Falls back to full LLM generation if all three sources fail.
    """
    session = session_store.get(session_id)
    if session is None:
        raise HTTPException(404, "Session not found. Upload a resume first.")

    try:
        questions = question_service.get_or_generate_questions(
            session, total=total, role=role, jd=jd
        )
    except Exception as e:
        logger.exception("Question generation failed")
        raise HTTPException(500, f"Question generation failed: {str(e)}")

    return {"questions": questions}


@router.get("/api/debug/chunks/{session_id}")
def debug_chunks(session_id: str):
    session = session_store.get(session_id)
    if session is None:
        raise HTTPException(404, "Session not found.")
    if "debug_chunks" not in session:
        raise HTTPException(400, "No chunks yet — generate questions first.")
    retrieval = session.get("debug_retrieval", {})
    return {
        # Raw section splits from the resume (label → text)
        "resume_sections": session["debug_chunks"],
        # What each source contributed
        "sources": {
            "dataset":  [q["question"] for q in retrieval.get("dataset", [])],
            "project":  [q["question"] for q in retrieval.get("project", [])],
            "hr":       [q["question"] for q in retrieval.get("hr", [])],
        },
    }
